project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "PalaeOpen"

  page-footer:
    left: "&copy; Copyright 2025, PalaeOpen"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/) by Ondřej Mottl."
  site-url: https://palaeopen.github.io/
  repo-url: https://github.com/PalaeOpen/PalaeOpen.github.io/
  issue-url: https://github.com/PalaeOpen/PalaeOpen.github.io/issues
  repo-actions: [source, issue]

  image: Materials/Logos/PalaeOpen_without_text.png
  favicon: Materials/Logos/PalaeOpen_without_text.png
  back-to-top-navigation: true

  navbar:
    logo: Materials/Logos/PalaeOpen_without_text.png
    left:
      - text: About
        menu:
          - text: General Information
            href: about.qmd
          - text: Working groups
            href: working_groups.qmd

      - text: Core Group
        href: coregroup.qmd

      - text: Events
        menu:
          - text: Prague 2025
            href: events/prague_2025.qmd
          - text: WG2 workshop - Macedonia 2025
            href: events/macedonia_wg2_2025.qmd

      - text: Outreach
        menu:
          - text: Press Release 2025
            href: outreach/press_release_2025.qmd
          - text: STMS blog posts
            href: grants/stms/stms_blog_posts.qmd
          - text: Meeting reports
            href: outreach/meetings/meeting_reports.qmd

      - text: Grants
        menu:
          - text: Open Call for STSM Grants
            href: grants/stms/stms_2026.qmd

      - text: Join Us
        href: join_us.qmd

    right:
      - text: Join us!
        href: https://e-services.cost.eu/action/CA23116/working-groups/applications

    tools:
      - icon: github
        href: https://github.com/PalaeOpen/

format:
  html:
    theme:
      - styles.scss
    toc: true
    toc-depth: 2
