project:
  type: website
  output-dir: docs

website:
  title: "PalaeOpen"

  page-navigation: true
  back-to-top-navigation: true

  page-footer:
    left: "&copy; Copyright 2025, PalaeOpen"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/) by Ondřej Mottl."

  site-url: https://palaeopen.github.io/
  repo-url: https://github.com/PalaeOpen/PalaeOpen.github.io/
  issue-url: https://github.com/PalaeOpen/PalaeOpen.github.io/issues
  repo-actions: [source, issue]

  image: Materials/Logos/PalaeOpen_without_text.png
  favicon: Materials/Logos/PalaeOpen_without_text.png

  navbar:
    title: PalaeOpen
    search: true
    logo: Materials/Logos/PalaeOpen_without_text.png
    left:
      - text: About
        menu:
          - text: General information
            href: About/about.qmd

      - href: coregroup.qmd
        text: Core Group

      - text: Working groups
        menu:
          - text: WG1 - Terrestrial proxies
            href: About/wg1.qmd
          - text: WG2 - Aquatic proxies
            href: About/wg2.qmd
          - text: WG3 - Infrastructure and Databases
            href: About/wg3.qmd
          - text: WG4 - Science communication
            href: About/wg4.qmd

      - text: Events
        menu:
          - text: Bulgaria Training 2026
            href: events/bulgaria_trainingschool_2026.qmd
          - text: Prague 2025
            href: events/prague_2025.qmd
          - text: WG2 workshop - Macedonia 2025
            href: events/macedonia_wg2_2025.qmd

      - text: Outreach
        menu:
          - text: Press Release 2025
            href: outreach/press_release_2025.qmd
          - text: STMS blog posts
            href: grants/stms/stms_blog_posts.qmd
          - text: Meeting reports
            href: outreach/meetings/meeting_reports.qmd

      - text: Grants
        menu:
          - text: Open Call for STSM Grants
            href: grants/stms/stms_2026.qmd

      - text: Join Us
        href: join_us.qmd

    right:
      - text: Join us!
        href: https://e-services.cost.eu/action/CA23116/working-groups/applications

    tools:
      - icon: github
        href: https://github.com/PalaeOpen/

format:
  html:
    theme:
      - styles.scss
    toc: true
    toc-depth: 2
